# Generated by Django 5.0.6 on 2024-05-26 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nepaliName', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1)),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='person/images')),
                ('birth', models.DateField(null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('aliveOrDead', models.CharField(max_length=7)),
                ('personId', models.ImageField(default=0, upload_to='')),
                ('pustaNumber', models.BigIntegerField(blank=True, null=True)),
                ('bookReferenceNumber', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=1000)),
                ('address', models.CharField(max_length=100)),
                ('cityOrCountry', models.CharField(max_length=100)),
                ('contactDetails', models.CharField(max_length=100)),
                ('emailAddress', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactOption', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('MobileNumber', 'MobileNumber'), ('HomeAddress', 'HomeAddress'), ('Email', 'Email')], default=None, max_length=15)),
                ('contactDetail', models.CharField(max_length=100)),
                ('primaryPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Son', 'Son'), ('Daughter', 'Daughter'), ('Spouse', 'Spouse')], default=None, max_length=8)),
                ('primaryPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_person', to='Person.person')),
                ('secondaryPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_person', to='Person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contactOption', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('MobileNumber', 'MobileNumber'), ('HomeAddress', 'HomeAddress'), ('Email', 'Email')], default=None, max_length=15)),
                ('contactDetail', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('primaryPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
        ),
    ]
