# Generated by Django 5.0.6 on 2024-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_alter_person_address_alter_person_cityorcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personId',
            field=models.IntegerField(default=0),
        ),
    ]
