# Generated by Django 5.0.6 on 2024-05-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_rename_contactdetail_suggestion_suggestorcontactdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrelationship',
            name='relation',
            field=models.CharField(choices=[('Father', 'Child'), ('Spouse', 'Spouse')], default=None, max_length=8),
        ),
    ]
